[package]
name = "dallo"
version = "0.1.0"
edition = "2021"

license = "MPL-2.0"

[dependencies]
rkyv = { version = "0.7.38", default-features = false, features = ["size_32", "alloc"] }

[features]
default = ["wasm"]
wasm = []
