[workspace]
members = [
    "box",
    "callcenter",
    "counter",
    "debugger",
    "eventer",
    "everest",    
    "fibonacci",    
    "host",
    "micro",
    "self_snapshot",
    "spender",
    "stack",
    "vector",
]
