[workspace]
members = [
    "box",
    "callcenter",
    "counter",
    "debugger",
    "eventer",
    "everest",
    "fallible_counter",    
    "fibonacci",
    "host",
    "micro",
    "self_snapshot",
    "spender",
    "stack",
    "vector",
]
