[package]
name = "piecrust"
description = """
Dusk's virtual machine for running WASM smart contracts.\
"""
categories = ["wasm", "no-std", "cryptography.categories.cryptocurrencies"]
keywords = ["virtual", "machine", "smart", "contract", "wasm"]

repository = "https://github.com/dusk-network/piecrust"
version = "0.1.0"

edition = "2021"

[dependencies]
piecrust-uplink = { version = "0.1", path = "../piecrust-uplink" }

wasmer = "3.1"
wasmer-vm = "3.1"
wasmer-types = "3.1"
wasmer-middlewares = "3.1"
wasmer-compiler-singlepass = "3.1"
bytecheck = "0.6"
rkyv = { version = "0.7", features = ["size_32", "validation"] }
parking_lot = "0.12"
blake3 = "1"
colored = "2"
libc = { version = "^0.2", default-features = false }
region = "3"
tempfile = "3"
thiserror = "1"
rand = "0.8"
bsdiff = "0.1.6"
zstd = "0.9"
hex = "0.4"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "stack"
harness = false
