[package]
name = "counter"
version = "0.1.0"
authors = [
    "Kristoffer Ström <kristoffer@dusk.network>",
]
edition = "2021"

[dependencies]
dallo = { path = "../../dallo" }

[lib]
crate-type = ["cdylib", "rlib"]
