[package]
name = "crumbles"
description = """
Keeping track of your pie's crumbles
"""
categories = ["data-structures", "memory-management"]
keywords = ["memory", "snapshots", "page", "dirty"]

repository = "https://github.com/dusk-network/piecrust"
version = "0.1.2"

edition = "2021"
license = "MPL-2.0"

[dependencies]
libc = "0.2"
rangemap = "1"
