[package]
name = "stack"
version = "0.1.0"
authors = [
    "Eduardo Leegwater Simões <eduardo@dusk.network>",
]
edition = "2021"

license = "MPL-2.0"

[dependencies]
dallo = { path = "../../dallo" }
nstack = { git = "ssh://git@github.com/dusk-network/nstack", branch = "ad-hoc-annotations" }
ranno = { git = "ssh://git@github.com/dusk-network/ranno", branch = "main", default-features = false, features = ["alloc"] }

[lib]
crate-type = ["cdylib", "rlib"]
